# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e65f9b7c795cfa619cc7561f6ca587fbf57e84a297805221c1cabd15dd81ab7baff385d0c74aacd099389c14c3ab3762b67bb6da3ff99a34622a113409594c90

test:
  secret_key_base: 7d139a2bcc38de35a8a0ea2def9e97ba46ebaf24a0e40d4c87f923cf7dd5872d109217a504abc5c5cdee5a288f23f1ef2768dd0accde9434975029f254ac8f21

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
